# Generated by Django 5.2 on 2025-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AddField(
            model_name='cor',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
